# Generated by Django 4.0.6 on 2022-07-28 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Music_Library',
            new_name='Music',
        ),
    ]
