# Generated by Django 4.0.6 on 2022-07-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_rename_music_library_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
